import { Inter } from "next/font/google";
import RootStyleRegistry from '../lib/AntdRegistry';
import "./globals.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App', // modify this
  description: 'Generated by create next app',  // modify this
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootStyleRegistry>
          {children}
        </RootStyleRegistry>
      </body>
    </html>
  )
}
