openapi: 3.0.0
info:
  title: Farmaze Backend API
  version: 1.0.0
paths:
  /b2bclients/summary:
    get:
      summary: Get a summary of B2B clients
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ID:
                      type: string
                      format: uuid
                    CompanyName:
                      type: string
                    ContactName:
                      type: string
                    Email:
                      type: string
                    PhoneNumber:
                      type: string
  /b2bclients/{client_id}:
    get:
      summary: Get details of a B2B client by ID
      parameters:
        - in: path
          name: client_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  ID:
                    type: string
                    format: uuid
                  CompanyName:
                    type: string
                  ContactName:
                    type: string
                  Email:
                    type: string
                  PhoneNumber:
                    type: string
  /products:
    get:
      summary: Get a list of all products
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ID:
                      type: string
                      format: uuid
                    Name:
                      type: string
                    Price:
                      type: number
                    Description:
                      type: string
                    AvailableQuantity:
                      type: integer
                    Category:
                      type: string
  /orders:
    post:
      summary: Create a new order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ClientID:
                  type: string
                  format: uuid
                Products:
                  type: array
                  items:
                    type: object
                    properties:
                      ProductID:
                        type: string
                        format: uuid
                      Quantity:
                        type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  ID:
                    type: string
                    format: uuid
                  ClientID:
                    type: string
                    format: uuid
                  Products:
                    type: array
                    items:
                      type: object
                      properties:
                        ProductID:
                          type: string
                          format: uuid
                        Quantity:
                          type: integer
                  TotalPrice:
                    type: number
                  CreatedAt:
                    type: string
                    format: date-time
                  Status:
                    type: string
                    format: uuid
    get:
      summary: Get a list of all orders
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ID:
                      type: string
                      format: uuid
                    ClientID:
                      type: string
                      format: uuid
                    Products:
                      type: array
                      items:
                        type: object
                        properties:
                          ProductID:
                            type: string
                            format: uuid
                          Quantity:
                            type: integer
                    TotalPrice:
                      type: number
                    CreatedAt:
                      type: string
                      format: date-time
                    Status:
                      type: string
                      format: uuid
  /orders/{client_id}:
    get:
      summary: Get orders by client ID
      parameters:
        - in: path
          name: client_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

