name: Build and Deploy to AWS EC2 with Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build Docker images with Docker Compose
        run: docker-compose build

      - name: Push API Docker image to registry
        run: |
          docker push bhuvanachin/farmaze-backend-api:latest
      - name: Add ECDSA SSH Key to Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" >> ~/.ssh/known_hosts

      # Optionally, push the DB image if you have a custom one

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to EC2 with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Sync the necessary files to the EC2 instance
            rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude='.git .github .nvm' ./ ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/

            # Navigate to the app directory and run Docker Compose
            cd /home/ec2-user/farmaze-backend/
            docker-compose pull
            docker-compose up -d