name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'  # Update to match the version in your go.mod file

      - name: Update Go modules
        run: |
          go mod tidy
          go mod download

      - name: Build the application
        run: go build -v -o farmaze-backend .

      - name: Copy the binary to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "farmaze-backend"
          target: "/home/ec2-user/app"

      - name: Restart the application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart myapp