name: Go Server CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o farmaze-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    
    steps:
    - name: Deploy to Server
      run: |
        mkdir -p ~/.ssh/
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -i ~/.ssh/id_rsa ./farmaze-backend user@your-server-ip:/path/to/deployment/folder